#ifndef PRIORITYQUEUE_GLOBAL_H
#define PRIORITYQUEUE_GLOBAL_H

#if defined(PRIORITYQUEUE_LIBRARY)
#  define PRIORITYQUEUESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRIORITYQUEUESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRIORITYQUEUE_GLOBAL_H
